# lextable.py. This file automatically created by PLY (version 3.10). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('DO', 'CONST', 'REALNUMBER', 'NOTEQUAL', 'STARSTAR', 'ASSIGNMENT', 'THEN', 'EQUAL', 'LABEL', 'CHAR', 'PBEGIN', 'WHILE', 'PROGRAM', 'REPEAT', 'VAR', 'STAR', 'DIV', 'WITH', 'MINUS', 'DOT', 'OTHERWISE', 'CASE', 'LE', 'RPAREN', 'SEMICOLON', 'TO', 'RBRAC', 'PLUS', 'DOTDOT', 'RECORD', 'LT', 'COLON', 'PACKED', 'HEXDIGSEQ', 'COMMA', 'ARRAY', 'IDENTIFIER', 'FUNCTION', 'COMMENT', 'GT', 'END', 'GOTO', 'FOR', 'UPARROW', 'ELSE', 'GE', 'SET', 'LPAREN', 'IN', 'FORWARD', 'UNTIL', 'PROCEDURE', 'IF', 'AND', 'OCTDIGSEQ', 'LBRAC', 'NIL', 'PFILE', 'OF', 'SLASH', 'UNPACKED', 'DOWNTO', 'BINDIGSEQ', 'STRING', 'NOT', 'DIGSEQ', 'TYPE', 'OR', 'MOD'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [("(?P<t_IDENTIFIER>[a-zA-Z]([a-zA-Z0-9])*)|(?P<t_CHAR>(\\'(([^\\\\\\'])|(\\\\[\\\\tn]))\\'))|(?P<t_STRING>(\\'((\\'(([^\\\\\\'])|(\\\\[\\\\tn]))*\\')|((([^\\\\\\'])|(\\\\[\\\\tn]))*))*\\'))|(?P<t_COMMENT>(?s)(\\(\\*.*?\\*\\))|({[^}]*}))|(?P<t_NEWLINE>\\n+)|(?P<t_REALNUMBER>(\\d+\\.\\d+([eE][\\+-]\\d+)?)|(\\d+[eE][\\+-]\\d+))|(?P<t_HEXDIGSEQ>(?i)[0-9][0-9a-f]*H)|(?P<t_OCTDIGSEQ>[0-7]+Q)|(?P<t_BINDIGSEQ>[01]+B)|(?P<t_DIGSEQ>[0-9]+)|(?P<t_ASSIGNMENT>:=)|(?P<t_STARSTAR>\\*\\*)|(?P<t_DOTDOT>\\.\\.)|(?P<t_GE>\\>\\=)|(?P<t_NOTEQUAL>\\<\\>)|(?P<t_LE>\\<\\=)|(?P<t_COLON>:)|(?P<t_COMMA>,)|(?P<t_LBRAC>\\[)|(?P<t_DOT>\\.)|(?P<t_GT>\\>)|(?P<t_EQUAL>\\=)|(?P<t_LPAREN>\\()|(?P<t_LT>\\<)|(?P<t_MINUS>\\-)|(?P<t_PLUS>\\+)|(?P<t_RBRAC>\\])|(?P<t_RPAREN>\\))|(?P<t_SEMICOLON>;)|(?P<t_SLASH>/)|(?P<t_STAR>\\*)|(?P<t_UPARROW>\\^)", [None, ('t_IDENTIFIER', 'IDENTIFIER'), None, ('t_CHAR', 'CHAR'), None, None, None, None, ('t_STRING', 'STRING'), None, None, None, None, None, None, None, None, None, None, ('t_COMMENT', 'COMMENT'), None, None, ('t_NEWLINE', 'NEWLINE'), ('t_REALNUMBER', 'REALNUMBER'), None, None, None, ('t_HEXDIGSEQ', 'HEXDIGSEQ'), ('t_OCTDIGSEQ', 'OCTDIGSEQ'), ('t_BINDIGSEQ', 'BINDIGSEQ'), ('t_DIGSEQ', 'DIGSEQ'), ('t_ASSIGNMENT', 'ASSIGNMENT'), ('t_STARSTAR', 'STARSTAR'), ('t_DOTDOT', 'DOTDOT'), ('t_GE', 'GE'), ('t_NOTEQUAL', 'NOTEQUAL'), ('t_LE', 'LE'), ('t_COLON', 'COLON'), ('t_COMMA', 'COMMA'), ('t_LBRAC', 'LBRAC'), ('t_DOT', 'DOT'), ('t_GT', 'GT'), ('t_EQUAL', 'EQUAL'), ('t_LPAREN', 'LPAREN'), ('t_LT', 'LT'), ('t_MINUS', 'MINUS'), ('t_PLUS', 'PLUS'), ('t_RBRAC', 'RBRAC'), ('t_RPAREN', 'RPAREN'), ('t_SEMICOLON', 'SEMICOLON'), ('t_SLASH', 'SLASH'), ('t_STAR', 'STAR'), ('t_UPARROW', 'UPARROW')])]}
_lexstateignore = {'INITIAL': ' \t\r\x0c'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
